#!/usr/bin/env perl
use Modern::Perl;
use open ':std', ':encoding(UTF-8)';
use utf8;

# takes a sorted wordlist on STDIN, e.g. /usr/share/dict/swiss

my %seen;
my $last = "\0";

for (<STDIN>) {
  chomp;
  $last = $_ if /f$/;
  $seen{$last} = 1 if /^$last[flijt]../;
}

# Watch out for -lich, -lisch, -los, -lein, -te, -ten … somehow?

for (sort keys %seen) {
  if (/graf$/) {
    # Biografie, Geografie: mit Ligatur für fi
    say "($_)([fljt]..)" ;
  } else {
    say "($_)([flijt]..)" ;
  }
}
