#!/usr/bin/env perl
use Modern::Perl;
use open ':std', ':encoding(UTF-8)';
use utf8;

=head1 NAME

keine-ligaturen

=head1 SYNOPSIS

    keine-ligaturen < input > output

=head1 DESCRIPTION

Add ligature-breaking ZERO WIDTH NON-JOINER to certain words. Create the
word-list at the end using C<keine-ligaturen-liste>.

To test it:

    keine-ligaturen < Farnthal.md | grep -P "\S+\x{200c}\S+"

=cut

my $zwnj = "\x{200c}";

my @re = grep !/^#/, map { chomp; $_ } <DATA>;
for my $line (<STDIN>) {
  for my $re (@re) {
    $line =~ s/\b$re/$1$zwnj$2/gi;
  }
  print $line;
}

__DATA__
(Ablauf)([flijt]\w\w)
(Auflauf)([flijt]\w\w)
(Baustoff)([flijt]\w\w)
(Binnenschiff)([flijt]\w\w)
(Biograf)([fljt]\w\w)
(Boxcalf)([flijt]\w\w)
(Boxkalf)([flijt]\w\w)
(Brief)([flijt]\w\w)
(Chef)([flijt]\w\w)
(Choreograf)([fljt]\w\w)
(Dampfschiff)([flijt]\w\w)
(Demograf)([fljt]\w\w)
(Dorf)([flijt]\w\w)
(Druckkopf)([flijt]\w\w)
(Filialchef)([flijt]\w\w)
(Fotograf)([fljt]\w\w)
(Futterstoff)([flijt]\w\w)
(Geldbrief)([flijt]\w\w)
(Geograf)([fljt]\w\w)
(Graf)([flijt]\w\w)
(Grundstoff)([flijt]\w\w)
(Handelsschiff)([flijt]\w\w)
(Hinterhof)([flijt]\w\w)
(Hof)([flijt]\w\w)
(Huf)([flijt]\w\w)
(Juniorchef)([flijt]\w\w)
(Kalligraf)([fljt]\w\w)
(Kampf)([flijt]\w\w)
(Kartograf)([fljt]\w\w)
(Kasernenhof)([flijt]\w\w)
(Knopf)([flijt]\w\w)
(Kopf)([flijt]\w\w)
(Kreislauf)([flijt]\w\w)
(Kremlchef)([flijt]\w\w)
(Kunststoff)([flijt]\w\w)
# (Prof)([flijt]\w\w)
(Ressortchef)([flijt]\w\w)
(Rohstoff)([flijt]\w\w)
(Sauerstoff)([flijt]\w\w)
(Schaf)([flijt]\w\w)
(Schiff)([flijt]\w\w)
(Schlupf)([flijt]\w\w)
(Stenograf)([fljt]\w\w)
(Stoff)([flijt]\w\w)
(Streif)([flijt]\w\w)
(Sumpf)([flijt]\w\w)
(Tarif)([flijt]\w\w)
(Telegraf)([fljt]\w\w)
(Treff)([flijt]\w\w)
(Typograf)([fljt]\w\w)
(Wahlkampf)([flijt]\w\w)
(Wurf)([flijt]\w\w)
(Zellstoff)([flijt]\w\w)
(Zukauf)([flijt]\w\w)
(auf)([flijt]\w\w)
(bedampf)([flijt]\w\w)
(begriff)([flijt]\w\w)
(behilf)([flijt]\w\w)
(beschaff)([flijt]\w\w)
(drauf)([flijt]\w\w)
(elf)([flijt]\w\w)
(erkauf)([flijt]\w\w)
(fünf)([flijt]\w\w)
(griff)([flijt]\w\w)
(half)([flijt]\w\w)
(herauf)([flijt]\w\w)
(hilf)([flijt]\w\w)
(hinauf)([flijt]\w\w)
(kauf)([flijt]\w\w)
(klopf)([flijt]\w\w)
(kläff)([flijt]\w\w)
(kniff)([flijt]\w\w)
(knöpf)([flijt]\w\w)
(knüpf)([flijt]\w\w)
(köpf)([flijt]\w\w)
(lauf)([flijt]\w\w)
(paff)([flijt]\w\w)
(pfiff)([flijt]\w\w)
(pfropf)([flijt]\w\w)
(raff)([flijt]\w\w)
(reif)([flijt]\w\w)
(rümpf)([flijt]\w\w)
(schaff)([flijt]\w\w)
(schief)([flijt]\w\w)
(schuf)([flijt]\w\w)
(seif)([flijt]\w\w)
(steif)([flijt]\w\w)
(straff)([flijt]\w\w)
(stuf)([flijt]\w\w)
(stumpf)([flijt]\w\w)
(tief)([flijt]\w\w)
(verkauf)([flijt]\w\w)
(verknüpf)([flijt]\w\w)
(verkrampf)([flijt]\w\w)
(verschaff)([flijt]\w\w)
(verschiff)([flijt]\w\w)
(verzapf)([flijt]\w\w)
(widerruf)([flijt]\w\w)
(zapf)([flijt]\w\w)
(zerstampf)([flijt]\w\w)
(zupf)([flijt]\w\w)
(zwölf)([flijt]\w\w)
