#!/usr/bin/env perl
use Modern::Perl;
use open ':std', ':encoding(UTF-8)';
use utf8;

=head1 NAME

keine-ligaturen-liste

=head1 SYNOPSIS

    keine-ligaturen-liste < /usr/share/dict/swiss >> keine-ligaturen

=head1 DESCRIPTION

Try and find German words that should have no ligatures joining to morphemes and
print a regular expression for C<keine-ligaturen>.

=cut

my %seen;
my $last = "\0";

for (<STDIN>) {
  chomp;
  $last = $_ if /f$/;
  $seen{$last} = 1 if /^$last[flijt]../;
}

# Watch out for -lich, -lisch, -los, -lein, -te, -ten … somehow?

for (sort keys %seen) {
  if (/graf$/) {
    # Biografie, Geografie: mit Ligatur für fi
    say "($_)([fljt]\\w\\w)" ;
  } else {
    say "($_)([flijt]\\w\\w)" ;
  }
}
